"""add_product_sale_category_fields

Revision ID: a32bccc3a709
Revises: 9e59a786623e
Create Date: 2026-07-09 11:36:06.809256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a32bccc3a709'
down_revision: Union[str, Sequence[str], None] = '9e59a786623e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('category_id', sa.String(), nullable=True))
    op.add_column('products', sa.Column('is_on_sale', sa.Boolean(), nullable=True))
    op.add_column('products', sa.Column('sale_price', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('sale_label', sa.String(), nullable=True))
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_column('products', 'sale_label')
    op.drop_column('products', 'sale_price')
    op.drop_column('products', 'is_on_sale')
    op.drop_column('products', 'category_id')
    # ### end Alembic commands ###
