"""add_ecommerce_fields_to_product

Revision ID: bdf77ab9a526
Revises: a32bccc3a709
Create Date: 2026-07-09 11:49:47.932092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdf77ab9a526'
down_revision: Union[str, Sequence[str], None] = 'a32bccc3a709'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('status', sa.String(), nullable=True))
    op.add_column('products', sa.Column('stock', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('weight', sa.String(), nullable=True))
    op.add_column('products', sa.Column('tags', sa.String(), nullable=True))
    op.add_column('products', sa.Column('vendor', sa.String(), nullable=True))
    op.add_column('products', sa.Column('seo_title', sa.String(), nullable=True))
    op.add_column('products', sa.Column('seo_description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'seo_description')
    op.drop_column('products', 'seo_title')
    op.drop_column('products', 'vendor')
    op.drop_column('products', 'tags')
    op.drop_column('products', 'weight')
    op.drop_column('products', 'stock')
    op.drop_column('products', 'status')
    # ### end Alembic commands ###
