import React from 'react';
import Header from '../components/Header';
import Footer from '../components/Footer';
import BottomNav from '../components/BottomNav';

const PrivacyPolicy: React.FC = () => {
  return (
    <div className="min-h-screen bg-[#FFF7F2] font-sans flex flex-col">
      <Header />
      
      <main className="flex-grow pt-8 pb-20 px-4 md:px-8 lg:px-12">
        <div className="max-w-4xl mx-auto bg-white p-8 md:p-12 rounded-2xl shadow-sm border border-[#D4AF37]/20">
          
          <h1 className="text-3xl md:text-5xl font-serif text-[#5F1517] mb-4">Privacy Policy for Siri Samruddhi Gold Palace</h1>
          <p className="text-sm text-[#5F1517]/60 italic mb-8">Last updated: July 18, 2026</p>

          <div className="prose prose-sm md:prose-base max-w-none text-gray-700 space-y-6">
            <p>
              This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
            </p>
            <p>
              We use Your Personal Data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
            </p>

            <h2 className="text-2xl font-serif text-[#5F1517] pt-4 border-t border-[#D4AF37]/20">Interpretation and Definitions</h2>
            
            <h3 className="text-xl font-bold text-[#801416]">Interpretation</h3>
            <p>
              The words whose initial letters are capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
            </p>

            <h3 className="text-xl font-bold text-[#801416]">Definitions</h3>
            <p>For the purposes of this Privacy Policy:</p>
            <ul className="list-disc pl-5 space-y-2">
              <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
              <li><strong>Affiliate</strong> means an entity that controls, is controlled by, or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
              <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Privacy Policy) refers to Siri Samruddhi Gold Palace.</li>
              <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
              <li><strong>Country</strong> refers to: Karnataka, India.</li>
              <li><strong>Device</strong> means any device that can access the Service such as a computer, a cell phone or a digital tablet.</li>
              <li><strong>Personal Data</strong> (or "Personal Information") is any information that relates to an identified or identifiable individual.</li>
              <li><strong>Service</strong> refers to the Website.</li>
              <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
              <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
              <li><strong>Website</strong> refers to Siri Samruddhi Gold Palace, accessible from <a href="http://sirisamruddhigold.com/" className="text-[#D4AF37] hover:underline">http://sirisamruddhigold.com/</a>.</li>
              <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
            </ul>

            <h2 className="text-2xl font-serif text-[#5F1517] pt-4 border-t border-[#D4AF37]/20">Collecting and Using Your Personal Data</h2>
            
            <h3 className="text-xl font-bold text-[#801416]">Types of Data Collected</h3>
            
            <h4 className="text-lg font-semibold text-[#5F1517]">Personal Data</h4>
            <p>
              While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
            </p>
            <ul className="list-disc pl-5 space-y-1">
              <li>Email address</li>
              <li>First name and last name</li>
              <li>Phone number</li>
              <li>Address, State, Province, ZIP/Postal code, City</li>
              <li>Usage Data</li>
            </ul>

            <h4 className="text-lg font-semibold text-[#5F1517]">Usage Data</h4>
            <p>Usage Data is collected automatically when using the Service.</p>
            <p>
              Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
            </p>
            <p>
              When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device's unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
            </p>

            <h3 className="text-xl font-bold text-[#801416]">Tracking Technologies and Cookies</h3>
            <p>
              We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies We use include beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:
            </p>
            <ul className="list-disc pl-5 space-y-2">
              <li><strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service.</li>
              <li><strong>Web Beacons.</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics.</li>
            </ul>
            <p>
              Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser.
            </p>

            <h3 className="text-xl font-bold text-[#801416]">Use of Your Personal Data</h3>
            <p>The Company may use Personal Data for the following purposes:</p>
            <ul className="list-disc pl-5 space-y-2">
              <li><strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service.</li>
              <li><strong>To manage Your Account:</strong> to manage Your registration as a user of the Service.</li>
              <li><strong>For the performance of a contract:</strong> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased.</li>
              <li><strong>To contact You:</strong> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication.</li>
              <li><strong>To provide You</strong> with news, special offers, and general information about other goods, services and events which We offer.</li>
              <li><strong>To manage Your requests:</strong> To attend and manage Your requests to Us.</li>
              <li><strong>For business transfers:</strong> We may use Your Personal Data to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale.</li>
              <li><strong>For other purposes:</strong> We may use Your information for other purposes, such as data analysis, identifying usage trends, and evaluating our Service.</li>
            </ul>

            <h3 className="text-xl font-bold text-[#801416]">Retention of Your Personal Data</h3>
            <p>
              The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies.
            </p>
            
            <h4 className="text-lg font-semibold text-[#5F1517]">Data Retention Periods</h4>
            <ul className="list-disc pl-5 space-y-2">
              <li><strong>User Accounts:</strong> retained for the duration of your account relationship plus up to 24 months after account closure.</li>
              <li><strong>Customer Support Data:</strong> up to 24 months from the date of ticket closure.</li>
              <li><strong>Usage Data:</strong> up to 24 months from the date of collection.</li>
              <li><strong>Server logs:</strong> up to 24 months for security monitoring and troubleshooting purposes.</li>
            </ul>

            <h3 className="text-xl font-bold text-[#801416]">Transfer of Your Personal Data</h3>
            <p>
              Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ from those from Your jurisdiction.
            </p>

            <h3 className="text-xl font-bold text-[#801416]">Delete Your Personal Data</h3>
            <p>
              You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You. Our Service may give You the ability to delete certain information about You from within the Service. You may update, amend, or delete Your information at any time by signing in to Your Account settings.
            </p>

            <h3 className="text-xl font-bold text-[#801416]">Disclosure of Your Personal Data</h3>
            <ul className="list-disc pl-5 space-y-2">
              <li><strong>Business Transactions:</strong> If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred.</li>
              <li><strong>Law enforcement:</strong> Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law.</li>
              <li><strong>Other legal requirements:</strong> To comply with a legal obligation, protect and defend rights, prevent wrongdoing, or protect personal safety.</li>
            </ul>

            <h2 className="text-2xl font-serif text-[#5F1517] pt-4 border-t border-[#D4AF37]/20">Security of Your Personal Data</h2>
            <p>
              The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially reasonable means to protect Your Personal Data, We cannot guarantee its absolute security.
            </p>

            <h2 className="text-2xl font-serif text-[#5F1517] pt-4 border-t border-[#D4AF37]/20">Children's Privacy</h2>
            <p>
              Our Service does not address anyone under the age of 16. We do not knowingly collect personally identifiable information from anyone under the age of 16. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us.
            </p>

            <h2 className="text-2xl font-serif text-[#5F1517] pt-4 border-t border-[#D4AF37]/20">Links to Other Websites</h2>
            <p>
              Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.
            </p>

            <h2 className="text-2xl font-serif text-[#5F1517] pt-4 border-t border-[#D4AF37]/20">Changes to this Privacy Policy</h2>
            <p>
              We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page. We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.
            </p>

            <h2 className="text-2xl font-serif text-[#5F1517] pt-4 border-t border-[#D4AF37]/20">Contact Us</h2>
            <p>If you have any questions about this Privacy Policy, You can contact us:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li>By email: <a href="mailto:sirisamruddhigold@gmail.com" className="text-[#D4AF37] hover:underline font-bold">sirisamruddhigold@gmail.com</a></li>
              <li>By phone: <a href="tel:9035085397" className="text-[#D4AF37] hover:underline font-bold">9035085397</a></li>
            </ul>

          </div>
        </div>
      </main>
      
      <Footer />
      <BottomNav />
    </div>
  );
};

export default PrivacyPolicy;
